name: Build Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in DockerHub
      run: echo "${{ secrets.DOCKERHUB }}" | docker login https://index.docker.io/v1/ -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: docker build . --tag cosckoya/go-prometheus:${GITHUB_SHA::8}
    - name: Image tag also as latest
      run: docker tag cosckoya/go-prometheus:${GITHUB_SHA::8} cosckoya/go-prometheus:latest
    - name: Push images
      run: docker push cosckoya/go-prometheus:latest && docker push cosckoya/go-prometheus:${GITHUB_SHA::8}
